version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: api-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: api-quiz
      POSTGRES_DB: api-quiz
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
